// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiskManagement.Infrastructure.Persistence;

#nullable disable

namespace RiskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiskManagement.Application.Sagas.ApplicationCreation.ApplicationCreationState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<bool>("AutoSubmit")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_submit");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CreditCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("credit_checked_at");

                    b.Property<string>("CreditProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("credit_provider");

                    b.Property<int?>("CreditScore")
                        .HasColumnType("integer")
                        .HasColumnName("credit_score");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_state");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("date_of_birth");

                    b.Property<double>("DesiredRate")
                        .HasColumnType("double precision")
                        .HasColumnName("desired_rate");

                    b.Property<string>("EmploymentStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("employment_status");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<double>("FixedCosts")
                        .HasColumnType("double precision")
                        .HasColumnName("fixed_costs");

                    b.Property<bool?>("HasPaymentDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("has_payment_default");

                    b.Property<double>("Income")
                        .HasColumnType("double precision")
                        .HasColumnName("income");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_email");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("CorrelationId");

                    b.ToTable("saga_application_creation_state", (string)null);
                });

            modelBuilder.Entity("RiskManagement.Domain.Aggregates.ApplicationAggregate.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<double>("DesiredRate")
                        .HasColumnType("double precision")
                        .HasColumnName("desired_rate");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("employment_status");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<double>("FixedCosts")
                        .HasColumnType("double precision")
                        .HasColumnName("fixed_costs");

                    b.Property<double>("Income")
                        .HasColumnType("double precision")
                        .HasColumnName("income");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessorComment")
                        .HasColumnType("text")
                        .HasColumnName("processor_comment");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int?>("ScoringConfigVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_config_version_id");

                    b.Property<string>("ScoringReasons")
                        .HasColumnType("text")
                        .HasColumnName("scoring_reasons");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TrafficLight")
                        .HasColumnType("text")
                        .HasColumnName("traffic_light");

                    b.HasKey("Id");

                    b.HasIndex("ScoringConfigVersionId");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("RiskManagement.Domain.Aggregates.ApplicationAggregate.ApplicationInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InquiryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inquiry_text");

                    b.Property<string>("ProcessorEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processor_email");

                    b.Property<string>("ResponseText")
                        .HasColumnType("text")
                        .HasColumnName("response_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("application_inquiries", (string)null);
                });

            modelBuilder.Entity("RiskManagement.Domain.Aggregates.ScoringConfigAggregate.ScoringConfigVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("scoring_config_versions", (string)null);
                });

            modelBuilder.Entity("RiskManagement.Domain.ReadModels.CustomerReadModel", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("CustomerId");

                    b.ToTable("customer_read_models", (string)null);
                });

            modelBuilder.Entity("RiskManagement.Domain.Aggregates.ApplicationAggregate.Application", b =>
                {
                    b.HasOne("RiskManagement.Domain.Aggregates.ScoringConfigAggregate.ScoringConfigVersion", null)
                        .WithMany()
                        .HasForeignKey("ScoringConfigVersionId");

                    b.OwnsOne("RiskManagement.Domain.ValueObjects.CreditReport", "CreditReport", b1 =>
                        {
                            b1.Property<int>("ApplicationId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("CheckedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("credit_checked_at");

                            b1.Property<int?>("CreditScore")
                                .HasColumnType("integer")
                                .HasColumnName("credit_score");

                            b1.Property<bool?>("HasPaymentDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("has_payment_default");

                            b1.Property<string>("Provider")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("credit_provider");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("CreditReport");
                });

            modelBuilder.Entity("RiskManagement.Domain.Aggregates.ApplicationAggregate.ApplicationInquiry", b =>
                {
                    b.HasOne("RiskManagement.Domain.Aggregates.ApplicationAggregate.Application", null)
                        .WithMany("Inquiries")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiskManagement.Domain.Aggregates.ScoringConfigAggregate.ScoringConfigVersion", b =>
                {
                    b.OwnsOne("RiskManagement.Domain.Aggregates.ScoringConfigAggregate.ScoringConfig", "Config", b1 =>
                        {
                            b1.Property<int>("ScoringConfigVersionId")
                                .HasColumnType("integer");

                            b1.Property<int>("GreenThreshold")
                                .HasColumnType("integer")
                                .HasColumnName("green_threshold");

                            b1.Property<decimal>("IncomeRatioGood")
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("income_ratio_good");

                            b1.Property<decimal>("IncomeRatioLimited")
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("income_ratio_limited");

                            b1.Property<decimal>("IncomeRatioModerate")
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("income_ratio_moderate");

                            b1.Property<int>("PenaltyCriticalRatio")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_critical_ratio");

                            b1.Property<int>("PenaltyExcessiveRate")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_excessive_rate");

                            b1.Property<int>("PenaltyHeavyRate")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_heavy_rate");

                            b1.Property<int>("PenaltyLimitedRatio")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_limited_ratio");

                            b1.Property<int>("PenaltyModerateRate")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_moderate_rate");

                            b1.Property<int>("PenaltyModerateRatio")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_moderate_ratio");

                            b1.Property<int>("PenaltyPaymentDefault")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_payment_default");

                            b1.Property<int>("PenaltyRetired")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_retired");

                            b1.Property<int>("PenaltySelfEmployed")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_self_employed");

                            b1.Property<int>("PenaltyUnemployed")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_unemployed");

                            b1.Property<decimal>("RateGood")
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("rate_good");

                            b1.Property<decimal>("RateHeavy")
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("rate_heavy");

                            b1.Property<decimal>("RateModerate")
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("rate_moderate");

                            b1.Property<int>("YellowThreshold")
                                .HasColumnType("integer")
                                .HasColumnName("yellow_threshold");

                            b1.HasKey("ScoringConfigVersionId");

                            b1.ToTable("scoring_config_versions");

                            b1.WithOwner()
                                .HasForeignKey("ScoringConfigVersionId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("RiskManagement.Domain.Aggregates.ApplicationAggregate.Application", b =>
                {
                    b.Navigation("Inquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
