// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiskManagement.Api.Data;

#nullable disable

namespace RiskManagement.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiskManagement.Api.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<double>("DesiredRate")
                        .HasColumnType("double precision")
                        .HasColumnName("desired_rate");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employment_status");

                    b.Property<double>("FixedCosts")
                        .HasColumnType("double precision")
                        .HasColumnName("fixed_costs");

                    b.Property<bool>("HasPaymentDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("has_payment_default");

                    b.Property<double>("Income")
                        .HasColumnType("double precision")
                        .HasColumnName("income");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProcessedAt")
                        .HasColumnType("text")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessorComment")
                        .HasColumnType("text")
                        .HasColumnName("processor_comment");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("ScoringReasons")
                        .HasColumnType("text")
                        .HasColumnName("scoring_reasons");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedAt")
                        .HasColumnType("text")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TrafficLight")
                        .HasColumnType("text")
                        .HasColumnName("traffic_light");

                    b.HasKey("Id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("RiskManagement.Api.Models.ApplicationInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InquiryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inquiry_text");

                    b.Property<string>("ProcessorEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processor_email");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("ResponseText")
                        .HasColumnType("text")
                        .HasColumnName("response_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("application_inquiries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
